<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class GnlUpazilasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $upazilas = DB::table('gnl_upazilas')->get();
        $sql = "INSERT INTO `gnl_upazilas` (`id`, `division_id`, `district_id`, `upazila_name`, `bn_name`, `url`, `is_active`, `is_delete`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES
        (1, NULL, 1, 'Debidwar', 'দেবিদ্বার', 'debidwar.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (2, NULL, 1, 'Barura', 'বরুড়া', 'barura.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (3, NULL, 1, 'Brahmanpara', 'ব্রাহ্মণপাড়া', 'brahmanpara.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (4, NULL, 1, 'Chandina', 'চান্দিনা', 'chandina.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (5, NULL, 1, 'Chauddagram', 'চৌদ্দগ্রাম', 'chauddagram.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (6, NULL, 1, 'Daudkandi', 'দাউদকান্দি', 'daudkandi.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (7, NULL, 1, 'Homna', 'হোমনা', 'homna.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (8, NULL, 1, 'Laksam', 'লাকসাম', 'laksam.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (9, NULL, 1, 'Muradnagar', 'মুরাদনগর', 'muradnagar.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (10, NULL, 1, 'Nangalkot', 'নাঙ্গলকোট', 'nangalkot.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (11, NULL, 1, 'Comilla Sadar', 'কুমিল্লা সদর', 'comillasadar.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (12, NULL, 1, 'Meghna', 'মেঘনা', 'meghna.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (13, NULL, 1, 'Monohargonj', 'মনোহরগঞ্জ', 'monohargonj.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (14, NULL, 1, 'Sadarsouth', 'সদর দক্ষিণ', 'sadarsouth.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (15, NULL, 1, 'Titas', 'তিতাস', 'titas.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (16, NULL, 1, 'Burichang', 'বুড়িচং', 'burichang.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (17, NULL, 1, 'Lalmai', 'লালমাই', 'lalmai.comilla.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (18, NULL, 2, 'Chhagalnaiya', 'ছাগলনাইয়া', 'chhagalnaiya.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (19, NULL, 2, 'Feni Sadar', 'ফেনী সদর', 'sadar.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (20, NULL, 2, 'Sonagazi', 'সোনাগাজী', 'sonagazi.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (21, NULL, 2, 'Fulgazi', 'ফুলগাজী', 'fulgazi.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (22, NULL, 2, 'Parshuram', 'পরশুরাম', 'parshuram.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (23, NULL, 2, 'Daganbhuiyan', 'দাগনভূঞা', 'daganbhuiyan.feni.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (24, NULL, 3, 'Brahmanbaria Sadar', 'ব্রাহ্মণবাড়িয়া সদর', 'sadar.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (25, NULL, 3, 'Kasba', 'কসবা', 'kasba.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (26, NULL, 3, 'Nasirnagar', 'নাসিরনগর', 'nasirnagar.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (27, NULL, 3, 'Sarail', 'সরাইল', 'sarail.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (28, NULL, 3, 'Ashuganj', 'আশুগঞ্জ', 'ashuganj.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (29, NULL, 3, 'Akhaura', 'আখাউড়া', 'akhaura.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (30, NULL, 3, 'Nabinagar', 'নবীনগর', 'nabinagar.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (31, NULL, 3, 'Bancharampur', 'বাঞ্ছারামপুর', 'bancharampur.brahmanbaria.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (32, NULL, 3, 'Bijoynagar', 'বিজয়নগর', 'bijoynagar.brahmanbaria.gov.bd    ', 1, 0, NULL, NULL, NULL, NULL),
        (33, NULL, 4, 'Rangamati Sadar', 'রাঙ্গামাটি সদর', 'sadar.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (34, NULL, 4, 'Kaptai', 'কাপ্তাই', 'kaptai.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (35, NULL, 4, 'Kawkhali', 'কাউখালী', 'kawkhali.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (36, NULL, 4, 'Baghaichari', 'বাঘাইছড়ি', 'baghaichari.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (37, NULL, 4, 'Barkal', 'বরকল', 'barkal.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (38, NULL, 4, 'Langadu', 'লংগদু', 'langadu.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (39, NULL, 4, 'Rajasthali', 'রাজস্থলী', 'rajasthali.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (40, NULL, 4, 'Belaichari', 'বিলাইছড়ি', 'belaichari.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (41, NULL, 4, 'Juraichari', 'জুরাছড়ি', 'juraichari.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (42, NULL, 4, 'Naniarchar', 'নানিয়ারচর', 'naniarchar.rangamati.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (43, NULL, 5, 'Noakhali Sadar', 'নোয়াখালী সদর', 'sadar.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (44, NULL, 5, 'Companiganj', 'কোম্পানীগঞ্জ', 'companiganj.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (45, NULL, 5, 'Begumganj', 'বেগমগঞ্জ', 'begumganj.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (46, NULL, 5, 'Hatia', 'হাতিয়া', 'hatia.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (47, NULL, 5, 'Subarnachar', 'সুবর্ণচর', 'subarnachar.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (48, NULL, 5, 'Kabirhat', 'কবিরহাট', 'kabirhat.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (49, NULL, 5, 'Senbug', 'সেনবাগ', 'senbug.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (50, NULL, 5, 'Chatkhil', 'চাটখিল', 'chatkhil.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (51, NULL, 5, 'Sonaimori', 'সোনাইমুড়ী', 'sonaimori.noakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (52, NULL, 6, 'Haimchar', 'হাইমচর', 'haimchar.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (53, NULL, 6, 'Kachua', 'কচুয়া', 'kachua.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (54, NULL, 6, 'Shahrasti', 'শাহরাস্তি	', 'shahrasti.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (55, NULL, 6, 'Chandpur Sadar', 'চাঁদপুর সদর', 'sadar.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (56, NULL, 6, 'Matlab South', 'মতলব দক্ষিণ', 'matlabsouth.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (57, NULL, 6, 'Hajiganj', 'হাজীগঞ্জ', 'hajiganj.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (58, NULL, 6, 'Matlab North', 'মতলব উত্তর', 'matlabnorth.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (59, NULL, 6, 'Faridgonj', 'ফরিদগঞ্জ', 'faridgonj.chandpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (60, NULL, 7, 'Lakshmipur Sadar', 'লক্ষ্মীপুর সদর', 'sadar.lakshmipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (61, NULL, 7, 'Kamalnagar', 'কমলনগর', 'kamalnagar.lakshmipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (62, NULL, 7, 'Raipur', 'রায়পুর', 'raipur.lakshmipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (63, NULL, 7, 'Ramgati', 'রামগতি', 'ramgati.lakshmipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (64, NULL, 7, 'Ramganj', 'রামগঞ্জ', 'ramganj.lakshmipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (65, NULL, 8, 'Rangunia', 'রাঙ্গুনিয়া', 'rangunia.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (66, NULL, 8, 'Sitakunda', 'সীতাকুন্ড', 'sitakunda.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (67, NULL, 8, 'Mirsharai', 'মীরসরাই', 'mirsharai.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (68, NULL, 8, 'Patiya', 'পটিয়া', 'patiya.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (69, NULL, 8, 'Sandwip', 'সন্দ্বীপ', 'sandwip.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (70, NULL, 8, 'Banshkhali', 'বাঁশখালী', 'banshkhali.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (71, NULL, 8, 'Boalkhali', 'বোয়ালখালী', 'boalkhali.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (72, NULL, 8, 'Anwara', 'আনোয়ারা', 'anwara.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (73, NULL, 8, 'Chandanaish', 'চন্দনাইশ', 'chandanaish.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (74, NULL, 8, 'Satkania', 'সাতকানিয়া', 'satkania.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (75, NULL, 8, 'Lohagara', 'লোহাগাড়া', 'lohagara.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (76, NULL, 8, 'Hathazari', 'হাটহাজারী', 'hathazari.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (77, NULL, 8, 'Fatikchhari', 'ফটিকছড়ি', 'fatikchhari.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (78, NULL, 8, 'Raozan', 'রাউজান', 'raozan.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (79, NULL, 8, 'Karnafuli', 'কর্ণফুলী', 'karnafuli.chittagong.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (80, NULL, 9, 'Coxsbazar Sadar', 'কক্সবাজার সদর', 'sadar.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (81, NULL, 9, 'Chakaria', 'চকরিয়া', 'chakaria.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (82, NULL, 9, 'Kutubdia', 'কুতুবদিয়া', 'kutubdia.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (83, NULL, 9, 'Ukhiya', 'উখিয়া', 'ukhiya.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (84, NULL, 9, 'Moheshkhali', 'মহেশখালী', 'moheshkhali.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (85, NULL, 9, 'Pekua', 'পেকুয়া', 'pekua.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (86, NULL, 9, 'Ramu', 'রামু', 'ramu.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (87, NULL, 9, 'Teknaf', 'টেকনাফ', 'teknaf.coxsbazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (88, NULL, 10, 'Khagrachhari Sadar', 'খাগড়াছড়ি সদর', 'sadar.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (89, NULL, 10, 'Dighinala', 'দিঘীনালা', 'dighinala.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (90, NULL, 10, 'Panchari', 'পানছড়ি', 'panchari.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (91, NULL, 10, 'Laxmichhari', 'লক্ষীছড়ি', 'laxmichhari.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (92, NULL, 10, 'Mohalchari', 'মহালছড়ি', 'mohalchari.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (93, NULL, 10, 'Manikchari', 'মানিকছড়ি', 'manikchari.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (94, NULL, 10, 'Ramgarh', 'রামগড়', 'ramgarh.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (95, NULL, 10, 'Matiranga', 'মাটিরাঙ্গা', 'matiranga.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (96, NULL, 10, 'Guimara', 'গুইমারা', 'guimara.khagrachhari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (97, NULL, 11, 'Bandarban Sadar', 'বান্দরবান সদর', 'sadar.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (98, NULL, 11, 'Alikadam', 'আলীকদম', 'alikadam.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (99, NULL, 11, 'Naikhongchhari', 'নাইক্ষ্যংছড়ি', 'naikhongchhari.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (100, NULL, 11, 'Rowangchhari', 'রোয়াংছড়ি', 'rowangchhari.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (101, NULL, 11, 'Lama', 'লামা', 'lama.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (102, NULL, 11, 'Ruma', 'রুমা', 'ruma.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (103, NULL, 11, 'Thanchi', 'থানচি', 'thanchi.bandarban.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (104, NULL, 12, 'Belkuchi', 'বেলকুচি', 'belkuchi.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (105, NULL, 12, 'Chauhali', 'চৌহালি', 'chauhali.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (106, NULL, 12, 'Kamarkhand', 'কামারখন্দ', 'kamarkhand.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (107, NULL, 12, 'Kazipur', 'কাজীপুর', 'kazipur.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (108, NULL, 12, 'Raigonj', 'রায়গঞ্জ', 'raigonj.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (109, NULL, 12, 'Shahjadpur', 'শাহজাদপুর', 'shahjadpur.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (110, NULL, 12, 'Sirajganj Sadar', 'সিরাজগঞ্জ সদর', 'sirajganjsadar.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (111, NULL, 12, 'Tarash', 'তাড়াশ', 'tarash.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (112, NULL, 12, 'Ullapara', 'উল্লাপাড়া', 'ullapara.sirajganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (113, NULL, 13, 'Sujanagar', 'সুজানগর', 'sujanagar.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (114, NULL, 13, 'Ishurdi', 'ঈশ্বরদী', 'ishurdi.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (115, NULL, 13, 'Bhangura', 'ভাঙ্গুড়া', 'bhangura.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (116, NULL, 13, 'Pabna Sadar', 'পাবনা সদর', 'pabnasadar.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (117, NULL, 13, 'Bera', 'বেড়া', 'bera.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (118, NULL, 13, 'Atghoria', 'আটঘরিয়া', 'atghoria.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (119, NULL, 13, 'Chatmohar', 'চাটমোহর', 'chatmohar.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (120, NULL, 13, 'Santhia', 'সাঁথিয়া', 'santhia.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (121, NULL, 13, 'Faridpur', 'ফরিদপুর', 'faridpur.pabna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (122, NULL, 14, 'Kahaloo', 'কাহালু', 'kahaloo.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (123, NULL, 14, 'Bogra Sadar', 'বগুড়া সদর', 'sadar.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (124, NULL, 14, 'Shariakandi', 'সারিয়াকান্দি', 'shariakandi.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (125, NULL, 14, 'Shajahanpur', 'শাজাহানপুর', 'shajahanpur.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (126, NULL, 14, 'Dupchanchia', 'দুপচাচিঁয়া', 'dupchanchia.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (127, NULL, 14, 'Adamdighi', 'আদমদিঘি', 'adamdighi.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (128, NULL, 14, 'Nondigram', 'নন্দিগ্রাম', 'nondigram.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (129, NULL, 14, 'Sonatala', 'সোনাতলা', 'sonatala.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (130, NULL, 14, 'Dhunot', 'ধুনট', 'dhunot.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (131, NULL, 14, 'Gabtali', 'গাবতলী', 'gabtali.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (132, NULL, 14, 'Sherpur', 'শেরপুর', 'sherpur.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (133, NULL, 14, 'Shibganj', 'শিবগঞ্জ', 'shibganj.bogra.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (134, NULL, 15, 'Paba', 'পবা', 'paba.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (135, NULL, 15, 'Durgapur', 'দুর্গাপুর', 'durgapur.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (136, NULL, 15, 'Mohonpur', 'মোহনপুর', 'mohonpur.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (137, NULL, 15, 'Charghat', 'চারঘাট', 'charghat.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (138, NULL, 15, 'Puthia', 'পুঠিয়া', 'puthia.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (139, NULL, 15, 'Bagha', 'বাঘা', 'bagha.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (140, NULL, 15, 'Godagari', 'গোদাগাড়ী', 'godagari.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (141, NULL, 15, 'Tanore', 'তানোর', 'tanore.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (142, NULL, 15, 'Bagmara', 'বাগমারা', 'bagmara.rajshahi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (143, NULL, 16, 'Natore Sadar', 'নাটোর সদর', 'natoresadar.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (144, NULL, 16, 'Singra', 'সিংড়া', 'singra.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (145, NULL, 16, 'Baraigram', 'বড়াইগ্রাম', 'baraigram.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (146, NULL, 16, 'Bagatipara', 'বাগাতিপাড়া', 'bagatipara.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (147, NULL, 16, 'Lalpur', 'লালপুর', 'lalpur.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (148, NULL, 16, 'Gurudaspur', 'গুরুদাসপুর', 'gurudaspur.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (149, NULL, 16, 'Naldanga', 'নলডাঙ্গা', 'naldanga.natore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (150, NULL, 17, 'Akkelpur', 'আক্কেলপুর', 'akkelpur.joypurhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (151, NULL, 17, 'Kalai', 'কালাই', 'kalai.joypurhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (152, NULL, 17, 'Khetlal', 'ক্ষেতলাল', 'khetlal.joypurhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (153, NULL, 17, 'Panchbibi', 'পাঁচবিবি', 'panchbibi.joypurhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (154, NULL, 17, 'Joypurhat Sadar', 'জয়পুরহাট সদর', 'joypurhatsadar.joypurhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (155, NULL, 18, 'Chapainawabganj Sadar', 'চাঁপাইনবাবগঞ্জ সদর', 'chapainawabganjsadar.chapainawabganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (156, NULL, 18, 'Gomostapur', 'গোমস্তাপুর', 'gomostapur.chapainawabganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (157, NULL, 18, 'Nachol', 'নাচোল', 'nachol.chapainawabganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (158, NULL, 18, 'Bholahat', 'ভোলাহাট', 'bholahat.chapainawabganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (159, NULL, 18, 'Shibganj', 'শিবগঞ্জ', 'shibganj.chapainawabganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (160, NULL, 19, 'Mohadevpur', 'মহাদেবপুর', 'mohadevpur.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (161, NULL, 19, 'Badalgachi', 'বদলগাছী', 'badalgachi.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (162, NULL, 19, 'Patnitala', 'পত্নিতলা', 'patnitala.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (163, NULL, 19, 'Dhamoirhat', 'ধামইরহাট', 'dhamoirhat.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (164, NULL, 19, 'Niamatpur', 'নিয়ামতপুর', 'niamatpur.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (165, NULL, 19, 'Manda', 'মান্দা', 'manda.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (166, NULL, 19, 'Atrai', 'আত্রাই', 'atrai.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (167, NULL, 19, 'Raninagar', 'রাণীনগর', 'raninagar.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (168, NULL, 19, 'Naogaon Sadar', 'নওগাঁ সদর', 'naogaonsadar.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (169, NULL, 19, 'Porsha', 'পোরশা', 'porsha.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (170, NULL, 19, 'Sapahar', 'সাপাহার', 'sapahar.naogaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (171, NULL, 20, 'Manirampur', 'মণিরামপুর', 'manirampur.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (172, NULL, 20, 'Abhaynagar', 'অভয়নগর', 'abhaynagar.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (173, NULL, 20, 'Bagherpara', 'বাঘারপাড়া', 'bagherpara.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (174, NULL, 20, 'Chougachha', 'চৌগাছা', 'chougachha.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (175, NULL, 20, 'Jhikargacha', 'ঝিকরগাছা', 'jhikargacha.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (176, NULL, 20, 'Keshabpur', 'কেশবপুর', 'keshabpur.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (177, NULL, 20, 'Jessore Sadar', 'যশোর সদর', 'sadar.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (178, NULL, 20, 'Sharsha', 'শার্শা', 'sharsha.jessore.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (179, NULL, 21, 'Assasuni', 'আশাশুনি', 'assasuni.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (180, NULL, 21, 'Debhata', 'দেবহাটা', 'debhata.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (181, NULL, 21, 'Kalaroa', 'কলারোয়া', 'kalaroa.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (182, NULL, 21, 'Satkhira Sadar', 'সাতক্ষীরা সদর', 'satkhirasadar.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (183, NULL, 21, 'Shyamnagar', 'শ্যামনগর', 'shyamnagar.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (184, NULL, 21, 'Tala', 'তালা', 'tala.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (185, NULL, 21, 'Kaliganj', 'কালিগঞ্জ', 'kaliganj.satkhira.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (186, NULL, 22, 'Mujibnagar', 'মুজিবনগর', 'mujibnagar.meherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (187, NULL, 22, 'Meherpur Sadar', 'মেহেরপুর সদর', 'meherpursadar.meherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (188, NULL, 22, 'Gangni', 'গাংনী', 'gangni.meherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (189, NULL, 23, 'Narail Sadar', 'নড়াইল সদর', 'narailsadar.narail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (190, NULL, 23, 'Lohagara', 'লোহাগড়া', 'lohagara.narail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (191, NULL, 23, 'Kalia', 'কালিয়া', 'kalia.narail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (192, NULL, 24, 'Chuadanga Sadar', 'চুয়াডাঙ্গা সদর', 'chuadangasadar.chuadanga.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (193, NULL, 24, 'Alamdanga', 'আলমডাঙ্গা', 'alamdanga.chuadanga.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (194, NULL, 24, 'Damurhuda', 'দামুড়হুদা', 'damurhuda.chuadanga.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (195, NULL, 24, 'Jibannagar', 'জীবননগর', 'jibannagar.chuadanga.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (196, NULL, 25, 'Kushtia Sadar', 'কুষ্টিয়া সদর', 'kushtiasadar.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (197, NULL, 25, 'Kumarkhali', 'কুমারখালী', 'kumarkhali.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (198, NULL, 25, 'Khoksa', 'খোকসা', 'khoksa.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (199, NULL, 25, 'Mirpur', 'মিরপুর', 'mirpurkushtia.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (200, NULL, 25, 'Daulatpur', 'দৌলতপুর', 'daulatpur.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (201, NULL, 25, 'Bheramara', 'ভেড়ামারা', 'bheramara.kushtia.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (202, NULL, 26, 'Shalikha', 'শালিখা', 'shalikha.magura.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (203, NULL, 26, 'Sreepur', 'শ্রীপুর', 'sreepur.magura.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (204, NULL, 26, 'Magura Sadar', 'মাগুরা সদর', 'magurasadar.magura.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (205, NULL, 26, 'Mohammadpur', 'মহম্মদপুর', 'mohammadpur.magura.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (206, NULL, 27, 'Paikgasa', 'পাইকগাছা', 'paikgasa.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (207, NULL, 27, 'Fultola', 'ফুলতলা', 'fultola.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (208, NULL, 27, 'Digholia', 'দিঘলিয়া', 'digholia.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (209, NULL, 27, 'Rupsha', 'রূপসা', 'rupsha.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (210, NULL, 27, 'Terokhada', 'তেরখাদা', 'terokhada.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (211, NULL, 27, 'Dumuria', 'ডুমুরিয়া', 'dumuria.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (212, NULL, 27, 'Botiaghata', 'বটিয়াঘাটা', 'botiaghata.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (213, NULL, 27, 'Dakop', 'দাকোপ', 'dakop.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (214, NULL, 27, 'Koyra', 'কয়রা', 'koyra.khulna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (215, NULL, 28, 'Fakirhat', 'ফকিরহাট', 'fakirhat.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (216, NULL, 28, 'Bagerhat Sadar', 'বাগেরহাট সদর', 'sadar.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (217, NULL, 28, 'Mollahat', 'মোল্লাহাট', 'mollahat.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (218, NULL, 28, 'Sarankhola', 'শরণখোলা', 'sarankhola.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (219, NULL, 28, 'Rampal', 'রামপাল', 'rampal.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (220, NULL, 28, 'Morrelganj', 'মোড়েলগঞ্জ', 'morrelganj.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (221, NULL, 28, 'Kachua', 'কচুয়া', 'kachua.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (222, NULL, 28, 'Mongla', 'মোংলা', 'mongla.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (223, NULL, 28, 'Chitalmari', 'চিতলমারী', 'chitalmari.bagerhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (224, NULL, 29, 'Jhenaidah Sadar', 'ঝিনাইদহ সদর', 'sadar.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (225, NULL, 29, 'Shailkupa', 'শৈলকুপা', 'shailkupa.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (226, NULL, 29, 'Harinakundu', 'হরিণাকুন্ডু', 'harinakundu.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (227, NULL, 29, 'Kaliganj', 'কালীগঞ্জ', 'kaliganj.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (228, NULL, 29, 'Kotchandpur', 'কোটচাঁদপুর', 'kotchandpur.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (229, NULL, 29, 'Moheshpur', 'মহেশপুর', 'moheshpur.jhenaidah.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (230, NULL, 30, 'Jhalakathi Sadar', 'ঝালকাঠি সদর', 'sadar.jhalakathi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (231, NULL, 30, 'Kathalia', 'কাঠালিয়া', 'kathalia.jhalakathi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (232, NULL, 30, 'Nalchity', 'নলছিটি', 'nalchity.jhalakathi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (233, NULL, 30, 'Rajapur', 'রাজাপুর', 'rajapur.jhalakathi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (234, NULL, 31, 'Bauphal', 'বাউফল', 'bauphal.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (235, NULL, 31, 'Patuakhali Sadar', 'পটুয়াখালী সদর', 'sadar.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (236, NULL, 31, 'Dumki', 'দুমকি', 'dumki.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (237, NULL, 31, 'Dashmina', 'দশমিনা', 'dashmina.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (238, NULL, 31, 'Kalapara', 'কলাপাড়া', 'kalapara.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (239, NULL, 31, 'Mirzaganj', 'মির্জাগঞ্জ', 'mirzaganj.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (240, NULL, 31, 'Galachipa', 'গলাচিপা', 'galachipa.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (241, NULL, 31, 'Rangabali', 'রাঙ্গাবালী', 'rangabali.patuakhali.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (242, NULL, 32, 'Pirojpur Sadar', 'পিরোজপুর সদর', 'sadar.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (243, NULL, 32, 'Nazirpur', 'নাজিরপুর', 'nazirpur.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (244, NULL, 32, 'Kawkhali', 'কাউখালী', 'kawkhali.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (245, NULL, 32, 'Zianagar', 'জিয়ানগর', 'zianagar.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (246, NULL, 32, 'Bhandaria', 'ভান্ডারিয়া', 'bhandaria.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (247, NULL, 32, 'Mathbaria', 'মঠবাড়ীয়া', 'mathbaria.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (248, NULL, 32, 'Nesarabad', 'নেছারাবাদ', 'nesarabad.pirojpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (249, NULL, 33, 'Barisal Sadar', 'বরিশাল সদর', 'barisalsadar.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (250, NULL, 33, 'Bakerganj', 'বাকেরগঞ্জ', 'bakerganj.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (251, NULL, 33, 'Babuganj', 'বাবুগঞ্জ', 'babuganj.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (252, NULL, 33, 'Wazirpur', 'উজিরপুর', 'wazirpur.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (253, NULL, 33, 'Banaripara', 'বানারীপাড়া', 'banaripara.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (254, NULL, 33, 'Gournadi', 'গৌরনদী', 'gournadi.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (255, NULL, 33, 'Agailjhara', 'আগৈলঝাড়া', 'agailjhara.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (256, NULL, 33, 'Mehendiganj', 'মেহেন্দিগঞ্জ', 'mehendiganj.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (257, NULL, 33, 'Muladi', 'মুলাদী', 'muladi.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (258, NULL, 33, 'Hizla', 'হিজলা', 'hizla.barisal.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (259, NULL, 34, 'Bhola Sadar', 'ভোলা সদর', 'sadar.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (260, NULL, 34, 'Borhan Sddin', 'বোরহান উদ্দিন', 'borhanuddin.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (261, NULL, 34, 'Charfesson', 'চরফ্যাশন', 'charfesson.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (262, NULL, 34, 'Doulatkhan', 'দৌলতখান', 'doulatkhan.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (263, NULL, 34, 'Monpura', 'মনপুরা', 'monpura.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (264, NULL, 34, 'Tazumuddin', 'তজুমদ্দিন', 'tazumuddin.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (265, NULL, 34, 'Lalmohan', 'লালমোহন', 'lalmohan.bhola.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (266, NULL, 35, 'Amtali', 'আমতলী', 'amtali.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (267, NULL, 35, 'Barguna Sadar', 'বরগুনা সদর', 'sadar.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (268, NULL, 35, 'Betagi', 'বেতাগী', 'betagi.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (269, NULL, 35, 'Bamna', 'বামনা', 'bamna.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (270, NULL, 35, 'Pathorghata', 'পাথরঘাটা', 'pathorghata.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (271, NULL, 35, 'Taltali', 'তালতলি', 'taltali.barguna.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (272, NULL, 36, 'Balaganj', 'বালাগঞ্জ', 'balaganj.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (273, NULL, 36, 'Beanibazar', 'বিয়ানীবাজার', 'beanibazar.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (274, NULL, 36, 'Bishwanath', 'বিশ্বনাথ', 'bishwanath.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (275, NULL, 36, 'Companiganj', 'কোম্পানীগঞ্জ', 'companiganj.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (276, NULL, 36, 'Fenchuganj', 'ফেঞ্চুগঞ্জ', 'fenchuganj.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (277, NULL, 36, 'Golapganj', 'গোলাপগঞ্জ', 'golapganj.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (278, NULL, 36, 'Gowainghat', 'গোয়াইনঘাট', 'gowainghat.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (279, NULL, 36, 'Jaintiapur', 'জৈন্তাপুর', 'jaintiapur.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (280, NULL, 36, 'Kanaighat', 'কানাইঘাট', 'kanaighat.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (281, NULL, 36, 'Sylhet Sadar', 'সিলেট সদর', 'sylhetsadar.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (282, NULL, 36, 'Zakiganj', 'জকিগঞ্জ', 'zakiganj.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (283, NULL, 36, 'Dakshinsurma', 'দক্ষিণ সুরমা', 'dakshinsurma.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (284, NULL, 36, 'Osmaninagar', 'ওসমানী নগর', 'osmaninagar.sylhet.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (285, NULL, 37, 'Barlekha', 'বড়লেখা', 'barlekha.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (286, NULL, 37, 'Kamolganj', 'কমলগঞ্জ', 'kamolganj.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (287, NULL, 37, 'Kulaura', 'কুলাউড়া', 'kulaura.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (288, NULL, 37, 'Moulvibazar Sadar', 'মৌলভীবাজার সদর', 'moulvibazarsadar.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (289, NULL, 37, 'Rajnagar', 'রাজনগর', 'rajnagar.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (290, NULL, 37, 'Sreemangal', 'শ্রীমঙ্গল', 'sreemangal.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (291, NULL, 37, 'Juri', 'জুড়ী', 'juri.moulvibazar.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (292, NULL, 38, 'Nabiganj', 'নবীগঞ্জ', 'nabiganj.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (293, NULL, 38, 'Bahubal', 'বাহুবল', 'bahubal.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (294, NULL, 38, 'Ajmiriganj', 'আজমিরীগঞ্জ', 'ajmiriganj.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (295, NULL, 38, 'Baniachong', 'বানিয়াচং', 'baniachong.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (296, NULL, 38, 'Lakhai', 'লাখাই', 'lakhai.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (297, NULL, 38, 'Chunarughat', 'চুনারুঘাট', 'chunarughat.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (298, NULL, 38, 'Habiganj Sadar', 'হবিগঞ্জ সদর', 'habiganjsadar.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (299, NULL, 38, 'Madhabpur', 'মাধবপুর', 'madhabpur.habiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (300, NULL, 39, 'Sunamganj Sadar', 'সুনামগঞ্জ সদর', 'sadar.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (301, NULL, 39, 'South Sunamganj', 'দক্ষিণ সুনামগঞ্জ', 'southsunamganj.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (302, NULL, 39, 'Bishwambarpur', 'বিশ্বম্ভরপুর', 'bishwambarpur.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (303, NULL, 39, 'Chhatak', 'ছাতক', 'chhatak.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (304, NULL, 39, 'Jagannathpur', 'জগন্নাথপুর', 'jagannathpur.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (305, NULL, 39, 'Dowarabazar', 'দোয়ারাবাজার', 'dowarabazar.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (306, NULL, 39, 'Tahirpur', 'তাহিরপুর', 'tahirpur.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (307, NULL, 39, 'Dharmapasha', 'ধর্মপাশা', 'dharmapasha.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (308, NULL, 39, 'Jamalganj', 'জামালগঞ্জ', 'jamalganj.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (309, NULL, 39, 'Shalla', 'শাল্লা', 'shalla.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (310, NULL, 39, 'Derai', 'দিরাই', 'derai.sunamganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (311, NULL, 40, 'Belabo', 'বেলাবো', 'belabo.narsingdi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (312, NULL, 40, 'Monohardi', 'মনোহরদী', 'monohardi.narsingdi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (313, NULL, 40, 'Narsingdi Sadar', 'নরসিংদী সদর', 'narsingdisadar.narsingdi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (314, NULL, 40, 'Palash', 'পলাশ', 'palash.narsingdi.gov.bd', 1, 0, NULL, 205, '2020-07-05 20:07:26', 205),
        (315, NULL, 40, 'Raipura', 'রায়পুরা', 'raipura.narsingdi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (316, NULL, 40, 'Shibpur', 'শিবপুর', 'shibpur.narsingdi.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (317, NULL, 41, 'Kaliganj', 'কালীগঞ্জ', 'kaliganj.gazipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (318, NULL, 41, 'Kaliakair', 'কালিয়াকৈর', 'kaliakair.gazipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (319, NULL, 41, 'Kapasia', 'কাপাসিয়া', 'kapasia.gazipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (320, NULL, 41, 'Gazipur Sadar', 'গাজীপুর সদর', 'sadar.gazipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (321, NULL, 41, 'Sreepur', 'শ্রীপুর', 'sreepur.gazipur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (322, NULL, 42, 'Shariatpur Sadar', 'শরিয়তপুর সদর', 'sadar.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (323, NULL, 42, 'Naria', 'নড়িয়া', 'naria.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (324, NULL, 42, 'Zajira', 'জাজিরা', 'zajira.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (325, NULL, 42, 'Gosairhat', 'গোসাইরহাট', 'gosairhat.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (326, NULL, 42, 'Bhedarganj', 'ভেদরগঞ্জ', 'bhedarganj.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (327, NULL, 42, 'Damudya', 'ডামুড্যা', 'damudya.shariatpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (328, NULL, 43, 'Araihazar', 'আড়াইহাজার', 'araihazar.narayanganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (329, NULL, 43, 'Bandar', 'বন্দর', 'bandar.narayanganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (330, NULL, 43, 'Narayanganj Sadar', 'নারায়নগঞ্জ সদর', 'narayanganjsadar.narayanganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (331, NULL, 43, 'Rupganj', 'রূপগঞ্জ', 'rupganj.narayanganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (332, NULL, 43, 'Sonargaon', 'সোনারগাঁ', 'sonargaon.narayanganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (333, NULL, 44, 'Basail', 'বাসাইল', 'basail.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (334, NULL, 44, 'Bhuapur', 'ভুয়াপুর', 'bhuapur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (335, NULL, 44, 'Delduar', 'দেলদুয়ার', 'delduar.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (336, NULL, 44, 'Ghatail', 'ঘাটাইল', 'ghatail.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (337, NULL, 44, 'Gopalpur', 'গোপালপুর', 'gopalpur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (338, NULL, 44, 'Madhupur', 'মধুপুর', 'madhupur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (339, NULL, 44, 'Mirzapur', 'মির্জাপুর', 'mirzapur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (340, NULL, 44, 'Nagarpur', 'নাগরপুর', 'nagarpur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (341, NULL, 44, 'Sakhipur', 'সখিপুর', 'sakhipur.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (342, NULL, 44, 'Tangail Sadar', 'টাঙ্গাইল সদর', 'tangailsadar.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (343, NULL, 44, 'Kalihati', 'কালিহাতী', 'kalihati.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (344, NULL, 44, 'Dhanbari', 'ধনবাড়ী', 'dhanbari.tangail.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (345, NULL, 45, 'Itna', 'ইটনা', 'itna.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (346, NULL, 45, 'Katiadi', 'কটিয়াদী', 'katiadi.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (347, NULL, 45, 'Bhairab', 'ভৈরব', 'bhairab.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (348, NULL, 45, 'Tarail', 'তাড়াইল', 'tarail.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (349, NULL, 45, 'Hossainpur', 'হোসেনপুর', 'hossainpur.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (350, NULL, 45, 'Pakundia', 'পাকুন্দিয়া', 'pakundia.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (351, NULL, 45, 'Kuliarchar', 'কুলিয়ারচর', 'kuliarchar.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (352, NULL, 45, 'Kishoreganj Sadar', 'কিশোরগঞ্জ সদর', 'kishoreganjsadar.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (353, NULL, 45, 'Karimgonj', 'করিমগঞ্জ', 'karimgonj.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (354, NULL, 45, 'Bajitpur', 'বাজিতপুর', 'bajitpur.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (355, NULL, 45, 'Austagram', 'অষ্টগ্রাম', 'austagram.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (356, NULL, 45, 'Mithamoin', 'মিঠামইন', 'mithamoin.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (357, NULL, 45, 'Nikli', 'নিকলী', 'nikli.kishoreganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (358, NULL, 46, 'Harirampur', 'হরিরামপুর', 'harirampur.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (359, NULL, 46, 'Saturia', 'সাটুরিয়া', 'saturia.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (360, NULL, 46, 'Manikganj Sadar', 'মানিকগঞ্জ সদর', 'sadar.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (361, NULL, 46, 'Gior', 'ঘিওর', 'gior.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (362, NULL, 46, 'Shibaloy', 'শিবালয়', 'shibaloy.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (363, NULL, 46, 'Doulatpur', 'দৌলতপুর', 'doulatpur.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (364, NULL, 46, 'Singiar', 'সিংগাইর', 'singiar.manikganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (365, NULL, 47, 'Savar', 'সাভার', 'savar.dhaka.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (366, NULL, 47, 'Dhamrai', 'ধামরাই', 'dhamrai.dhaka.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (367, NULL, 47, 'Keraniganj', 'কেরাণীগঞ্জ', 'keraniganj.dhaka.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (368, NULL, 47, 'Nawabganj', 'নবাবগঞ্জ', 'nawabganj.dhaka.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (369, NULL, 47, 'Dohar', 'দোহার', 'dohar.dhaka.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (370, NULL, 48, 'Munshiganj Sadar', 'মুন্সিগঞ্জ সদর', 'sadar.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (371, NULL, 48, 'Sreenagar', 'শ্রীনগর', 'sreenagar.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (372, NULL, 48, 'Sirajdikhan', 'সিরাজদিখান', 'sirajdikhan.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (373, NULL, 48, 'Louhajanj', 'লৌহজং', 'louhajanj.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (374, NULL, 48, 'Gajaria', 'গজারিয়া', 'gajaria.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (375, NULL, 48, 'Tongibari', 'টংগীবাড়ি', 'tongibari.munshiganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (376, NULL, 49, 'Rajbari Sadar', 'রাজবাড়ী সদর', 'sadar.rajbari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (377, NULL, 49, 'Goalanda', 'গোয়ালন্দ', 'goalanda.rajbari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (378, NULL, 49, 'Pangsa', 'পাংশা', 'pangsa.rajbari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (379, NULL, 49, 'Baliakandi', 'বালিয়াকান্দি', 'baliakandi.rajbari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (380, NULL, 49, 'Kalukhali', 'কালুখালী', 'kalukhali.rajbari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (381, NULL, 50, 'Madaripur Sadar', 'মাদারীপুর সদর', 'sadar.madaripur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (382, NULL, 50, 'Shibchar', 'শিবচর', 'shibchar.madaripur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (383, NULL, 50, 'Kalkini', 'কালকিনি', 'kalkini.madaripur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (384, NULL, 50, 'Rajoir', 'রাজৈর', 'rajoir.madaripur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (385, NULL, 51, 'Gopalganj Sadar', 'গোপালগঞ্জ সদর', 'sadar.gopalganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (386, NULL, 51, 'Kashiani', 'কাশিয়ানী', 'kashiani.gopalganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (387, NULL, 51, 'Tungipara', 'টুংগীপাড়া', 'tungipara.gopalganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (388, NULL, 51, 'Kotalipara', 'কোটালীপাড়া', 'kotalipara.gopalganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (389, NULL, 51, 'Muksudpur', 'মুকসুদপুর', 'muksudpur.gopalganj.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (390, NULL, 52, 'Faridpur Sadar', 'ফরিদপুর সদর', 'sadar.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (391, NULL, 52, 'Alfadanga', 'আলফাডাঙ্গা', 'alfadanga.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (392, NULL, 52, 'Boalmari', 'বোয়ালমারী', 'boalmari.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (393, NULL, 52, 'Sadarpur', 'সদরপুর', 'sadarpur.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (394, NULL, 52, 'Nagarkanda', 'নগরকান্দা', 'nagarkanda.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (395, NULL, 52, 'Bhanga', 'ভাঙ্গা', 'bhanga.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (396, NULL, 52, 'Charbhadrasan', 'চরভদ্রাসন', 'charbhadrasan.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (397, NULL, 52, 'Madhukhali', 'মধুখালী', 'madhukhali.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (398, NULL, 52, 'Saltha', 'সালথা', 'saltha.faridpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (399, NULL, 53, 'Panchagarh Sadar', 'পঞ্চগড় সদর', 'panchagarhsadar.panchagarh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (400, NULL, 53, 'Debiganj', 'দেবীগঞ্জ', 'debiganj.panchagarh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (401, NULL, 53, 'Boda', 'বোদা', 'boda.panchagarh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (402, NULL, 53, 'Atwari', 'আটোয়ারী', 'atwari.panchagarh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (403, NULL, 53, 'Tetulia', 'তেতুলিয়া', 'tetulia.panchagarh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (404, NULL, 54, 'Nawabganj', 'নবাবগঞ্জ', 'nawabganj.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (405, NULL, 54, 'Birganj', 'বীরগঞ্জ', 'birganj.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (406, NULL, 54, 'Ghoraghat', 'ঘোড়াঘাট', 'ghoraghat.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (407, NULL, 54, 'Birampur', 'বিরামপুর', 'birampur.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (408, NULL, 54, 'Parbatipur', 'পার্বতীপুর', 'parbatipur.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (409, NULL, 54, 'Bochaganj', 'বোচাগঞ্জ', 'bochaganj.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (410, NULL, 54, 'Kaharol', 'কাহারোল', 'kaharol.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (411, NULL, 54, 'Fulbari', 'ফুলবাড়ী', 'fulbari.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (412, NULL, 54, 'Dinajpur Sadar', 'দিনাজপুর সদর', 'dinajpursadar.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (413, NULL, 54, 'Hakimpur', 'হাকিমপুর', 'hakimpur.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (414, NULL, 54, 'Khansama', 'খানসামা', 'khansama.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (415, NULL, 54, 'Birol', 'বিরল', 'birol.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (416, NULL, 54, 'Chirirbandar', 'চিরিরবন্দর', 'chirirbandar.dinajpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (417, NULL, 55, 'Lalmonirhat Sadar', 'লালমনিরহাট সদর', 'sadar.lalmonirhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (418, NULL, 55, 'Kaliganj', 'কালীগঞ্জ', 'kaliganj.lalmonirhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (419, NULL, 55, 'Hatibandha', 'হাতীবান্ধা', 'hatibandha.lalmonirhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (420, NULL, 55, 'Patgram', 'পাটগ্রাম', 'patgram.lalmonirhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (421, NULL, 55, 'Aditmari', 'আদিতমারী', 'aditmari.lalmonirhat.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (422, NULL, 56, 'Syedpur', 'সৈয়দপুর', 'syedpur.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (423, NULL, 56, 'Domar', 'ডোমার', 'domar.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (424, NULL, 56, 'Dimla', 'ডিমলা', 'dimla.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (425, NULL, 56, 'Jaldhaka', 'জলঢাকা', 'jaldhaka.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (426, NULL, 56, 'Kishorganj', 'কিশোরগঞ্জ', 'kishorganj.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (427, NULL, 56, 'Nilphamari Sadar', 'নীলফামারী সদর', 'nilphamarisadar.nilphamari.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (428, NULL, 57, 'Sadullapur', 'সাদুল্লাপুর', 'sadullapur.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (429, NULL, 57, 'Gaibandha Sadar', 'গাইবান্ধা সদর', 'gaibandhasadar.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (430, NULL, 57, 'Palashbari', 'পলাশবাড়ী', 'palashbari.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (431, NULL, 57, 'Saghata', 'সাঘাটা', 'saghata.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (432, NULL, 57, 'Gobindaganj', 'গোবিন্দগঞ্জ', 'gobindaganj.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (433, NULL, 57, 'Sundarganj', 'সুন্দরগঞ্জ', 'sundarganj.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (434, NULL, 57, 'Phulchari', 'ফুলছড়ি', 'phulchari.gaibandha.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (435, NULL, 58, 'Thakurgaon Sadar', 'ঠাকুরগাঁও সদর', 'thakurgaonsadar.thakurgaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (436, NULL, 58, 'Pirganj', 'পীরগঞ্জ', 'pirganj.thakurgaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (437, NULL, 58, 'Ranisankail', 'রাণীশংকৈল', 'ranisankail.thakurgaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (438, NULL, 58, 'Haripur', 'হরিপুর', 'haripur.thakurgaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (439, NULL, 58, 'Baliadangi', 'বালিয়াডাঙ্গী', 'baliadangi.thakurgaon.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (440, NULL, 59, 'Rangpur Sadar', 'রংপুর সদর', 'rangpursadar.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (441, NULL, 59, 'Gangachara', 'গংগাচড়া', 'gangachara.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (442, NULL, 59, 'Taragonj', 'তারাগঞ্জ', 'taragonj.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (443, NULL, 59, 'Badargonj', 'বদরগঞ্জ', 'badargonj.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (444, NULL, 59, 'Mithapukur', 'মিঠাপুকুর', 'mithapukur.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (445, NULL, 59, 'Pirgonj', 'পীরগঞ্জ', 'pirgonj.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (446, NULL, 59, 'Kaunia', 'কাউনিয়া', 'kaunia.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (447, NULL, 59, 'Pirgacha', 'পীরগাছা', 'pirgacha.rangpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (448, NULL, 60, 'Kurigram Sadar', 'কুড়িগ্রাম সদর', 'kurigramsadar.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (449, NULL, 60, 'Nageshwari', 'নাগেশ্বরী', 'nageshwari.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (450, NULL, 60, 'Bhurungamari', 'ভুরুঙ্গামারী', 'bhurungamari.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (451, NULL, 60, 'Phulbari', 'ফুলবাড়ী', 'phulbari.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (452, NULL, 60, 'Rajarhat', 'রাজারহাট', 'rajarhat.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (453, NULL, 60, 'Ulipur', 'উলিপুর', 'ulipur.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (454, NULL, 60, 'Chilmari', 'চিলমারী', 'chilmari.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (455, NULL, 60, 'Rowmari', 'রৌমারী', 'rowmari.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (456, NULL, 60, 'Charrajibpur', 'চর রাজিবপুর', 'charrajibpur.kurigram.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (457, NULL, 61, 'Sherpur Sadar', 'শেরপুর সদর', 'sherpursadar.sherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (458, NULL, 61, 'Nalitabari', 'নালিতাবাড়ী', 'nalitabari.sherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (459, NULL, 61, 'Sreebordi', 'শ্রীবরদী', 'sreebordi.sherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (460, NULL, 61, 'Nokla', 'নকলা', 'nokla.sherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (461, NULL, 61, 'Jhenaigati', 'ঝিনাইগাতী', 'jhenaigati.sherpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (462, NULL, 62, 'Fulbaria', 'ফুলবাড়ীয়া', 'fulbaria.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (463, NULL, 62, 'Trishal', 'ত্রিশাল', 'trishal.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (464, NULL, 62, 'Bhaluka', 'ভালুকা', 'bhaluka.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (465, NULL, 62, 'Muktagacha', 'মুক্তাগাছা', 'muktagacha.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (466, NULL, 62, 'Mymensingh Sadar', 'ময়মনসিংহ সদর', 'mymensinghsadar.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (467, NULL, 62, 'Dhobaura', 'ধোবাউড়া', 'dhobaura.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (468, NULL, 62, 'Phulpur', 'ফুলপুর', 'phulpur.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (469, NULL, 62, 'Haluaghat', 'হালুয়াঘাট', 'haluaghat.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (470, NULL, 62, 'Gouripur', 'গৌরীপুর', 'gouripur.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (471, NULL, 62, 'Gafargaon', 'গফরগাঁও', 'gafargaon.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (472, NULL, 62, 'Iswarganj', 'ঈশ্বরগঞ্জ', 'iswarganj.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (473, NULL, 62, 'Nandail', 'নান্দাইল', 'nandail.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (474, NULL, 62, 'Tarakanda', 'তারাকান্দা', 'tarakanda.mymensingh.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (475, NULL, 63, 'Jamalpur Sadar', 'জামালপুর সদর', 'jamalpursadar.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (476, NULL, 63, 'Melandah', 'মেলান্দহ', 'melandah.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (477, NULL, 63, 'Islampur', 'ইসলামপুর', 'islampur.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (478, NULL, 63, 'Dewangonj', 'দেওয়ানগঞ্জ', 'dewangonj.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (479, NULL, 63, 'Sarishabari', 'সরিষাবাড়ী', 'sarishabari.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (480, NULL, 63, 'Madarganj', 'মাদারগঞ্জ', 'madarganj.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (481, NULL, 63, 'Bokshiganj', 'বকশীগঞ্জ', 'bokshiganj.jamalpur.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (482, NULL, 64, 'Barhatta', 'বারহাট্টা', 'barhatta.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (483, NULL, 64, 'Durgapur', 'দুর্গাপুর', 'durgapur.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (484, NULL, 64, 'Kendua', 'কেন্দুয়া', 'kendua.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (485, NULL, 64, 'Atpara', 'আটপাড়া', 'atpara.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (486, NULL, 64, 'Madan', 'মদন', 'madan.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (487, NULL, 64, 'Khaliajuri', 'খালিয়াজুরী', 'khaliajuri.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (488, NULL, 64, 'Kalmakanda', 'কলমাকান্দা', 'kalmakanda.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (489, NULL, 64, 'Mohongonj', 'মোহনগঞ্জ', 'mohongonj.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (490, NULL, 64, 'Purbadhala', 'পূর্বধলা', 'purbadhala.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (491, NULL, 64, 'Netrokona Sadar', 'নেত্রকোণা সদর', 'netrokonasadar.netrokona.gov.bd', 1, 0, NULL, NULL, NULL, NULL),
        (492, NULL, 8, 'Rangpur Sador 1', NULL, NULL, 1, 0, '2020-01-13 21:20:15', NULL, '2020-01-13 21:20:29', NULL),
        (493, NULL, 10, 'Gangachara', NULL, NULL, 1, 0, '2020-01-13 21:30:24', NULL, '2020-01-13 21:31:28', NULL),
        (494, NULL, 62, 'test', NULL, NULL, 1, 1, '2020-02-16 14:45:22', 1, '2020-02-16 08:45:31', 1),
        (495, NULL, 66, 'GanGA', NULL, NULL, 1, 0, '2020-02-22 15:17:37', 1, '2020-02-22 09:17:37', NULL),
        (496, NULL, 47, 'Demra', NULL, NULL, 1, 0, '2020-07-04 18:25:19', 242, '2020-07-04 22:25:19', NULL),
        (497, NULL, 47, 'Jatrabari', NULL, NULL, 1, 0, '2020-07-04 18:25:51', 242, '2020-07-04 22:25:51', NULL),
        (498, NULL, 40, 'Narsindi sodor', NULL, NULL, 1, 0, '2020-07-05 16:06:56', 144, '2020-07-05 20:35:03', 144),
        (499, NULL, 67, 'Arihajer', NULL, NULL, 1, 0, '2020-07-05 16:21:00', 281, '2020-07-06 13:58:13', 281),
        (500, NULL, 67, 'Araihazar', NULL, NULL, 1, 0, '2020-07-06 10:17:11', 281, '2020-07-06 14:17:11', NULL),
        (501, NULL, 40, 'Madhobdi', NULL, NULL, 1, 0, '2020-07-06 12:48:26', 162, '2020-07-06 16:48:26', NULL),
        (502, NULL, 69, 'rupgonj', NULL, NULL, 1, 0, '2020-07-06 13:59:44', 94, '2020-07-06 17:59:44', NULL),
        (503, 6, 43, 'Siddirgonj', NULL, NULL, 1, 0, '2020-08-20 15:29:01', 296, '2020-08-20 19:29:01', NULL),
        (504, 6, 43, 'Fotulla', NULL, NULL, 1, 0, '2020-08-20 15:29:39', 296, '2020-08-20 19:29:39', NULL),
        (505, 6, 47, 'Sabujbag', NULL, NULL, 1, 0, '2020-09-20 08:48:24', 296, '2020-09-20 12:48:24', NULL),
        (506, 6, 47, 'Khilgaon', NULL, NULL, 1, 0, '2020-09-20 08:48:53', 296, '2020-09-20 12:48:53', NULL),
        (507, 6, 47, 'Demra', NULL, NULL, 1, 1, '2020-09-20 08:49:15', 296, '2020-09-20 13:12:09', 296),
        (508, 6, 43, 'Rupgonj', NULL, NULL, 1, 1, '2020-09-20 08:49:38', 296, '2020-09-20 13:24:20', 296),
        (509, 6, 40, 'Ramchandur', NULL, NULL, 1, 0, '2020-09-28 12:44:20', 296, '2020-09-28 16:44:55', 296)";
        if (count($upazilas) == 0) {
            DB::insert($sql);
        }
    }
}
