@extends('Layouts.erp_master')
@section('content')
<?php
use App\Services\CommonService;

    $headR=0;
    $branchR=0;
?>


<form enctype="multipart/form-data" method="post" class="form-horizontal" 
    data-toggle="validator" novalidate="true"vautocomplete="off"> 
    @csrf      
    <div class="row">
        <div class="col-lg-8 offset-lg-3">


            
            <div class="form-row form-group align-items-center">
                <label class="col-lg-3 input-title RequiredStar">Select Module</label>
                <div class="col-lg-5">
                    <div class="input-group">
                        <input type="text" class="form-control round" 
                        data-error="Title name  required" value="{{$module_data->module_name}}" readonly
                       placeholder="Enter Title">
                    </div>
                    <div class="help-block with-errors is-invalid"></div>
                </div>
            </div>
            
        
        </div>
    </div>
    <input type="hidden"  name="module_id"  value="{{$module_id}}">
       <!--Head Office Details -->
       <div class="panel panel-default">
        <div class="panel-heading p-2 mb-4">Head Office</div>
        <div class="panel-body">
            <div class="row text-right p-10">
                <div class="col-lg-12 text-right">
                 
                    
                    <a href="javascript:void(0)" id="btnSearch" onclick="btnAddNewRowhead();"  class="btn btn-primary btn-round">Add New Row</a>
                </div>
            </div>
            <div class="row"> 
                
        
                <div class="col-lg-12 offset-lg-1" id="headDivID">
                    <div class="row" >
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Title Name</label>
                           <div class="input-group">
                                <input type="text" class="form-control round" 
                                 data-error="Title name  required" value="Generated By" readonly
                                placeholder="Enter Title">
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Select Designation</label>
                            <div class="input-group">
                                <input type="text" class="form-control round"
                                data-error="Title name  required" value="Logged In User" readonly
                               placeholder="Enter Title">
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        <div class="col-lg-2 form-group">
                            <label class="input-title">Select Employee</label>
                            <div class="input-group">
                                <input type="text" class="form-control round"
                                data-error="Title name  required" value="Logged In User" readonly
                               placeholder="Enter Title">
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                       
                        
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Order </label>
                            <div class="input-group">
                                <input type="text" class="form-control round"
                                data-error="Title name  required" value="At the End" readonly
                               placeholder="Enter Title">
                            </div>
                            
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                      
                       
                    </div> 
                   
                    @foreach ($headData as $row)
                    <div class="row" id="row_head_{{$headR}}">
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Title Name</label>
                            <div class="input-group">
                                <input type="text" class="form-control round" id="head_title_{{$headR}}" name="head_title[]"
                                  data-error="Title name  required"
                                placeholder="Enter Title" value="{{$row->title}}" required>
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Select Designation</label>
                            <div class="input-group">
                                <select class="form-control clsSelect2" name="head_signatorDesignationId[]" id="head_signatorDesignationId_{{$headR}}" 
                                     data-error="Please Select Product" onchange="fnChangeEmployeeHead({{$headR}});" required>
                                    <option value="">Select</option>
                                    @foreach($EmpDesignations as $des)
                                    <option value="{{ $des->id }}"}} {{($row->signatorDesignationId == $des->id)? "selected":""}}>{{ $des->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        <div class="col-lg-2 form-group">
                            <label class="input-title">Select Employee</label>
                            <div class="input-group">
                                <select class="form-control clsSelect2" name="head_signatorEmployeeId[]" id="head_signatorEmployeeId_{{$headR}}"
                                     data-error="Please Select Product">
                                    <option value="">Select</option>
                                    @foreach($employeeData as $data)
                                    <option value="{{ $data->id }}"}} {{(isset($row->signatorEmployeeId) && $row->signatorEmployeeId == $data->id)? "selected":""}}>{{ $data->emp_name }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        
                        <div class="col-lg-2 form-group">
                            <label class="input-title RequiredStar">Order </label>
                            <div class="input-group">
                                <input type="text" class="form-control round" id="head_positionOrder_0" name="head_positionOrder[]"
                                      data-error="Order is required" required
                                    placeholder="Enter Order" value="{{isset($row->positionOrder)? $row->positionOrder : '' }}">
                            </div>
                            
                            <div class="help-block with-errors is-invalid"></div>
                        </div>
                        <div class="col-lg-2 form-group">                            
                            <label class="input-title"></label>
                            <div class="input-group">
                                <a href="javascript:void(0)" onclick="btnRemoveRowHead({{$headR}});"  class="btn btn-danger btn-round">Remove</a>

                            </div>
                            
                        </div>
                        
                       
                    </div>

                    <?php $headR ++ ;?>
                    
                    @endforeach
                    <input type="hidden" id="headtotalRow" value="{{$headR}}">
                    
                </div>
            </div>
            
        </div>
    </div>

    <!-- Branch Details -->
<div class="panel panel-default">
    <div class="panel-heading p-2 mb-4">Branch Office</div>
    <div class="panel-body">
        <div class="row text-right p-10">
            <div class="col-lg-12 text-right">
             
                
                <a href="javascript:void(0)" id="btnSearch" onclick="btnAddNewRowbranch();"  class="btn btn-primary btn-round">Add New Row</a>
            </div>
        </div>
        <div class="row"> 
            
    
            <div class="col-lg-12 offset-lg-1" id="branchDivID">
                <div class="row" >
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Title Name</label>
                       <div class="input-group">
                            <input type="text" class="form-control round" 
                             data-error="Title name  required" value="Generated By" readonly
                            placeholder="Enter Title">
                        </div>
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Select Designation</label>
                        <div class="input-group">
                            <input type="text" class="form-control round"
                            data-error="Title name  required" value="Logged In User" readonly
                           placeholder="Enter Title">
                        </div>
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                   
                   
                    
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Order </label>
                        <div class="input-group">
                            <input type="text" class="form-control round"
                            data-error="Title name  required" value="At the End" readonly
                           placeholder="Enter Title">
                        </div>
                        
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                  
                   
                </div> 
                
               
                @foreach ($branchData as $row)
                <div class="row" id="row_branch_{{$branchR}}">
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Title Name</label>
                        <div class="input-group">
                            <input type="text" class="form-control round" id="branch_title_{{$branchR}}" name="branch_title[]"
                              data-error="Title name  required" value="{{$row->title}}" required
                            placeholder="Enter Title">
                        </div>
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Select Designation</label>
                        <div class="input-group">
                            <select class="form-control clsSelect2" name="branch_signatorDesignationId[]" id="branch_signatorDesignationId_{{$branchR}}" 
                                 data-error="Please Select Product" required>
                                <option value="">Select</option>
                                @foreach($EmpDesignations as $des)
                                <option value="{{ $des->id }}"}} {{($row->signatorDesignationId == $des->id)? "selected":""}}>{{ $des->name }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                    
                    
                    <div class="col-lg-2 form-group">
                        <label class="input-title RequiredStar">Order </label>
                        <div class="input-group">
                            <input type="text" class="form-control round" id="branch_positionOrder_{{$branchR}}" name="branch_positionOrder[]"
                                  data-error="Order is required" value="{{isset($row->positionOrder)? $row->positionOrder : '' }}"
                                placeholder="Enter Order" required>
                        </div>
                        
                        <div class="help-block with-errors is-invalid"></div>
                    </div>
                    <div class="col-lg-2 form-group">                            
                        <label class="input-title"></label>
                        <div class="input-group">
                            <a href="javascript:void(0)" onclick="btnRemoveRowBranch({{$branchR}});"  class="btn btn-danger btn-round">Remove</a>

                        </div>
                        
                    </div>
                   
                </div>

                <?php $branchR ++ ;?>
                @endforeach
                <input type="hidden" id="branchtotalRow" value="{{$branchR}}">
            </div>
        </div>
        
    </div>
</div>

    @include('elements.button.common_button', ['back' => true, 'submit' => [
                            'action' => 'update',
                            'title' => 'update',
                            'exClass' => 'float-right'
                        ]])
</form>
    
<script type="text/javascript">
    
    function fnChangeEmployeeHead(Row){
      
        var id = "head_signatorEmployeeId_" + Row;
        var value = $("#head_signatorDesignationId_" + Row).val();
        if (value == '') {
            return false;
        }

        let sqlite = "{{ (CommonService::getDBConnection() == 'sqlite') ? 1 : 0 }}";

        if(sqlite == 1){
            fnAjaxSelectBox(id,
                value,
                '{{base64_encode("hr_employees")}}',
                '{{base64_encode("designation_id")}}',
                '{{base64_encode("id,employee_no,emp_name,emp_code")}}',
                '{{url("/ajaxSelectBox")}}', null, 'isActiveOff'
            );
        }
        else{
            fnAjaxSelectBox(id,
                value,
                '{{base64_encode("hr_employees")}}',
                '{{base64_encode("designation_id")}}',
                '{{base64_encode("id,emp_name,emp_code")}}',
                '{{url("/ajaxSelectBox")}}', null, 'isActiveOff'
            );
        }
    }
    
  
    
    function btnAddNewRowhead() {
    
    
       
        var total_row = $('#headtotalRow').val();



        

        var html = '';

        html += ' <div class="row" id="row_head_'+total_row+'">';

        html += '<div class="col-lg-2 form-group"><label class="input-title RequiredStar">Title Name</label><div class="input-group">';
        html += '<input type="text" class="form-control round" id="head_title_'+total_row+'" required name="head_title[]" data-error="Title name  required" placeholder="Enter Title">';
        html += '</div><div class="help-block with-errors is-invalid"></div></div> <div class="col-lg-2 form-group"> <label class="input-title RequiredStar">Select Designation</label> <div class="input-group">';
        html += '<select class="form-control clsSelect2" required name="head_signatorDesignationId[]" id="head_signatorDesignationId_'+total_row+'" data-error="Please Select Product" onchange="fnChangeEmployeeHead('+total_row+');">';
        html += '<option value="">Select</option> @foreach($EmpDesignations as $des) <option value="{{ $des->id }}"}}>{{ $des->name }}</option>  @endforeach </select>';
        html += '</div><div class="help-block with-errors is-invalid"></div> </div><div class="col-lg-2 form-group"> <label class="input-title">Select Employee</label>';
                        

        html += '<div class="input-group"><select class="form-control clsSelect2" name="head_signatorEmployeeId[]" id="head_signatorEmployeeId_'+total_row+'" data-error="Please Select Product">';
        html += ' <option value="">Select</option> </select></div> <div class="help-block with-errors is-invalid"></div></div>';
                    
                    
        
        html += '<div class="col-lg-2 form-group"><label class="input-title RequiredStar">Order </label><div class="input-group">';
        html += '<input type="text" class="form-control round" id="head_positionOrder_'+total_row+'" required name="head_positionOrder[]" data-error="Order is required" placeholder="Enter Order">';               
        html += '</div><div class="help-block with-errors is-invalid"></div> </div>';               
                        
        html += '<div class="col-lg-2 form-group"><label class="input-title"></label> <div class="input-group">';
        html += '<a href="javascript:void(0)" onclick="btnRemoveRowHead('+total_row+');"  class="btn btn-danger btn-round">Remove</a></div></div>';
        total_row ++;

        $('#headtotalRow').val(total_row);
        $('#headDivID').append(html);

        
    }
    function btnAddNewRowbranch() {
    
    
       
    var total_row = $('#branchtotalRow').val();
    
    // total_row ++;
    
    
    
    
    var html = '';
    
    html += ' <div class="row" id="row_branch_'+total_row+'">';
    
    html += '<div class="col-lg-2 form-group"><label class="input-title RequiredStar">Title Name</label><div class="input-group">';
    html += '<input type="text" class="form-control round" id="branch_title" name="branch_title[]" required data-error="Title name  required" placeholder="Enter Title">';
    html += '</div><div class="help-block with-errors is-invalid"></div></div> <div class="col-lg-2 form-group"> <label class="input-title RequiredStar">Select Designation</label> <div class="input-group">';
    html += '<select class="form-control clsSelect2" name="branch_signatorDesignationId[]"  required id="branch_signatorDesignationId_'+total_row+'"  data-error="Please Select Product" onchange="fnChangeEmployeeBranch('+total_row+');">';
    html += '<option value="">Select</option> @foreach($EmpDesignations as $des) <option value="{{ $des->id }}"}}>{{ $des->name }}</option>  @endforeach </select>';
    html += '</div><div class="help-block with-errors is-invalid"></div> </div>';
                    
            
    html += '<div class="col-lg-2 form-group"><label class="input-title">Order </label><div class="input-group">';
    html += '<input type="text" class="form-control round" id="branch_positionOrder_'+total_row+'" name="branch_positionOrder[]" required data-error="Order is required" placeholder="Enter Order">';               
    html += '</div><div class="help-block with-errors is-invalid"></div> </div>';               
                    
    
    html += '<div class="col-lg-2 form-group"><label class="input-title"></label> <div class="input-group">';
    html += '<a href="javascript:void(0)" onclick="btnRemoveRowBranch('+total_row+');"  class="btn btn-danger btn-round">Remove</a></div></div>';


            total_row ++;

    $('#branchtotalRow').val(total_row);
    $('#branchDivID').append(html);
    
    
    
    }
    
 function btnRemoveRowBranch(RemoveID) {

    $('#row_branch_'+RemoveID).remove();
}

function btnRemoveRowHead(RemoveID) {
     console.log('dddddd');
    $('#row_head_'+RemoveID).remove();
}  
    </script>

@endsection
